# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.CharField(default=datetime.date(2018, 12, 2), max_length=1000),
        ),
    ]
